### ISSUE TITLE
Fixing ivm-compiler

### ISSUE THREAD

**Issue by trgwii** [immortalvm/ivm-apps#12]
If I look into this I will open relevant PR's in
[ivm-compiler](https://github.com/immortalvm/ivm-compiler)

ivm-apps (lib portion) does not compile using the latest ivm-compiler (3.4). I
have been using the recommended 2.0 version for these demos, but I should
probably bisect them to find where the bug was introduced at some point.

Fix ivm-apps and / or the compiler to eliminate the current dual-build situation
(building ivm-apps "lib" with ivm-compiler 2.0, and building ivm-apps "app" with
ivm-compiler 3.4)

**Comment by elnv** [comment]
We have checked this issue, and we believe  that the lastest version of compiler (3.4) works perfectly fine.

The issue found, when compiling ivm-apps, may be caused by the library's  'configure'  script, that tries to guess some features (data type size, perhaps) by creating files. But the IVM filesystem implementation is virtual, that is, it's an in-RAM filesystem, and  these files obviously don't exist on the host machine.

The project needs to be adapted to be cross-compiled (or remove our support for filesystem (ivmfs) in the newlib libc library, which is not to very advisable). The build process cannot assume that the target machine has a persistent filesystem.

This is why older ivm compiler versions work for this build, because they don't support filesystem for target executables, and probably default values for data size are used instead.

We also recommend to use the lastest version of the IVM architecture (2.1) and have a look at the ivm64-as as an alternative to building binaries, and ivm64-emu for a faster execution. 

Remember that the program generated by  the compiler behaves like a true executable if the ivm assembler and emulator are in the path, thanks to an included shebang than invokes them. In this case the env variables IVM_OUTDIR and IVM_INDIR must be defined with the paths where image files are located.

**Comment by trgwii** [comment]
Last time I tested I think it was libtiff failing to generate a tiffio.h header because some autoconf checks checking for size of builtin types produced no output on 3.4, but worked perfectly fine on 2.0. There's no rush just now, but if you want I can try to isolate and reproduce the exact issue

**Comment by trgwii** [comment]
After re-reading your comment I think I understand better what you mean, that sounds like it could be the case. In any case I think everything around the core compiler and spec and yet-another-fast-ivm-emulator is very solid. Just these projects cobbling all these libraries together to do stuff are a bit more unstable. Ease of development will be important if we want externally-contributed file formats.

**Comment by elnv** [comment]
In the last version of the compiler we included an empty ivmfs by default in newlib libc (as generated by ivm64-fsgen), in order to execute programs using filesystem primitives.

In the case of libtiff, it seems that some test files are created during the configuration to store the size of data types, but although these test programs execute fine (if the emulator is found in PATH), the files don't persist (ivmfs is a virtual in-ram fs). We believe this is causing the problem.  (Older versions didn't have fs and the configure test programs failed, so the sizes were set to a default value).

In general the configuration process would be adapted for cross-compilation rather than modifying the compiler libraries.

A trick may be to remove the empty filesystem included by default in libc when building ivm-apps before compiling:
```sh
    ar d $(find $(dirname $(which ivm64-gcc))/..  -iname "libc.a") 00-ivmfs-empty.o
```
This allowed us to compile the current ivm-app project with the lastest version of the compiler (3.4).

Although the empty file system is removed, this is not a problem as a new one can be created using the ivmfs generator (```ivm64-fsgen```) which is also available with the compiler (in addition to being an independent [repository](https://github.com/immortalvm/ivm-fs)). 

We suggest to try the assembler ```ivm64-as``` (as alternative to ivm as) (also distributed with the compiler).

Perhaps these slides from a previous meeting can help to clarify the toolchain with the ivm in-ram filesystem: 
[tech-meeting-15jan2024.pdf](https://github.com/user-attachments/files/17966833/tech-meeting-15jan2024.pdf)

**Comment by trgwii** [comment]
Alright. thanks for the slides. I agree with you, I think the current compiler behavior is probably best for general compatibility, and I think we can close this as the changes required to fix libtiff should be done in ivm-apps rather than elsewhere.
